### ISSUE TITLE
catch/rethrow of Exception leads to seemingly inappropriate messages

### ISSUE THREAD

**Issue by rwv37** [CSharpAnalyzers/ExceptionalReSharper#44]
If you catch Exception just to try to do some logging or something, and then rethrow it, you get several messages from Exceptional, none of which seem terribly appropriate in this particular type of usage.  

Additionally, and I think more importantly, you can't suppress them.  But I'll open that up as another ticket.

Example:

```
    public void Blah()
    {
        try
        {
            Console.WriteLine("Doing something");
        }
        catch (Exception e)
        {
            Console.WriteLine("Oh no! " + e.Message);
            throw;
        }
```

That gets:

(1) Usage of catch-all clauses is not recommended
(2) Exception 'Exception' is not documented
(3) Throwing 'System.Exception' is not recommended

**Comment by pedromagueija** [comment]
@rwv37 I think it "depends" on the take on Exceptions. Unfortunately, like many things in our industry, there isn't only one answer.

Exceptional tries to help you, in notifying of potential undocumented/unhandled exceptions. It can't tell whether it makes sense or not to document it at that point in your code. That's a developer decision.

When a "squiggle" is shown, we should read it more like a question:
There is a potential exception here, have I done enough to inform me or others of it, or I have I done enough that my program does not fail catastrophically?

If you are sure that at that point all the above is met, then, by all means, suppress the warnings (see my reply to your other issue).

Does this help?

**Comment by rwv37** [comment]
Sure, that's reasonable, but the suppressions aren't working (see my reply to your reply to my other issue).

**Comment by cmeeren** [comment]
I'm also of the strong opinion that catching and re-throwing should not produce warnings. The example shown in the OP is AFAIK a common way of logging exceptions. As long as you re-throw them, there's no harm done here. Furthermore, it's also AFAIK common to catch one or several places along the stack, add relevant data to the `Data` property, and re-throw.

Again, as long as you re-throw the same exception using `throw;`, I don't see what the pitfalls could be.

**Comment by pedromagueija** [comment]
I think we all agree with that view. 
The point of the OP was whether Exceptional should show a squiggle for the re-thrown Exception.
That is where I think it should since there is a potential for an exception to occur, and that should be documented for others using the method.

Do you agree?

**Comment by cmeeren** [comment]
Referring to the OPs list, my (admittedly not that experienced) opinion is this:

> (1) Usage of catch-all clauses is not recommended

This **should not** be shown as long as you re-throw using `throw;`, which means the exception will continue to propagate upwards.

> (2) Exception 'Exception' is not documented

This **should** be shown, since you are, potentially, throwing (or passing on) any type of exception, including `System.Expection`.

> (3) Throwing 'System.Exception' is not recommended

This **should not** be shown, since (correct me if I'm wrong) by using `throw;` you're not really throwing `Exception`, you're passing on whatever exception comes your way. And if that happens to be `System.Exception`, then this catch-rethrow block is not where the error is.

**Comment by pedromagueija** [comment]
Well, the more I think about it, the more I'm convinced you're right when a `throw;` is used.

For point 1, one could argue that we are not really catching the exception (I think that is your point, right?);
For point 2, we both agree;
For point 3, it's true at runtime (you might have a derived exception) but at compile time we can't know that, but since it is not the source of the exception then it should be ok.

I'm convinced, so if no one else objects then I'll try to get it in for the next version.

Thanks.

**Comment by rsuter** [comment]
I also agree with @cmeeren's list...

**Comment by cmeeren** [comment]
> For point 1, one could argue that we are not really catching the exception (I think that is your point, right?);

Correct.
